application: taiwan-airmap
version: 1-1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: /image/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /json/airmap\.json
  script: public/g0vAirmapJson.php

- url: /json/(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)

- url: /site
  script: public/site.php

- url: /.*
  script: public/map.php

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^(node_modules/.*)
- ^(.git/.*)